server:
  port: 8088

accessKeyId: LTAIcALRhtiNQWNr
accessKeySecret:  HfhZ146o4ZbCkNwap8edmEd0phPwGE

#mq.brokerURL=failover:(tcp://172.20.1.230:61616,tcp://172.20.1.231:61616,tcp://172.20.1.232:61616)?randomize=false&connectionTimeout=10000
#spring.activemq.broker-url=tcp://172.20.1.154:61616
#spring.activemq.user=ryx
#spring.activemq.password=ryx
spring:
  activemq:
    broker-url: tcp://10.0.0.26:61616
